UPDATE LCSSEASONPRODUCTLINK spl1
SET spl1.att27 =
(select LCSSKU.att12
from LCSSKU,LCSSEASONPRODUCTLINK spl2
where LCSSKU. BRANCHIDITERATIONINFO = spl2.SKUAREVID
and spl2.SEASONLINKTYPE = ‘SKU’
and LCSSKU.VERSIONIDA2VERSIONINFO = ‘A’
and LCSSKU.LATESTITERATIONINFO = 1
and spl1.ida2a2 = spl2.ida2a2